(require 'window-purpose)
(require 'ess-site)
(defun open-r-project ()
  (interactive)
  (setq ess-ask-for-ess-directory nil)
  (setq ess-directory "~/Documents/R_Project/")
  (R)
  (purpose-load-frame-layout "~/.emacs.d/.Rlayout")
)

(global-set-key (kbd "C-c r") 'open-r-project)
